name: Test pipeline

on: [push]

permissions:
  id-token: write
  contents: read

jobs:   
  workflow-test:
    name: 'Set purview permissions with workflow'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Set current client id as root collection admin'
        run:  |
          az config set extension.use_dynamic_install=yes_without_prompt
          az purview account add-root-collection-admin --name "abeebu"  --object-id ${{ secrets.AZURE_CLIENT_ID }}
        shell: bash

      - name: Set purview permissions
        uses: ./ 
        id: purview-permissions
        with:
          purview_name: "abeebu"
          object_id: "fb3d1d54-235e-4217-866c-1e1095863bb9"
          user_type: "U"
          roles: "root_collection_admin"

