name: Test pipeline

on: [push]

permissions:
  id-token: write
  contents: read

jobs:   
  workflow-test:
    name: 'Set purview permissions with workflow'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: 'Az CLI login'
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set purview permissions
        uses: ./
        id: purview-permissions
        with:
          purview_name: "abeebu"
          object_id: "9cd56d35-21ac-40c8-9bec-1a1055cf73c0"
          user_type: "U"
          roles: "root_collection_admin,data_reader,data_curator"