name: Test pipeline

on: [push]

permissions:
  id-token: write
  contents: read

jobs:   
  workflow-test:
    name: 'Set purview permissions with workflow'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set purview permissions
        uses: ./ 
        id: purview-permissions
        with:
          purview_name: "abeeb"
          object_id: "id"
          user_type: "U"
          roles: |
            root_collection_admin
            data_reader
            data_source_admin

